// Auto-generated by deployment scripts — do not edit manually
// After deploying contracts, these addresses will be populated.

export const CONTRACTS = {
  MEGICULA_TOKEN_ADDRESS: "0x8012c673D5cb57522Fe8f97AB1f9b93A54359a67",
  MEGICULA_STAKING_ADDRESS: "0x6699A1022e6caC639247446206eDFe0ae545710e",
} as const;

export const NETWORK = {
  CHAIN_ID: 984,
  RPC_URL: "https://testnet-rpc.iopn.tech",
  EXPLORER_URL: "https://testnet.opnscan.io",
  NAME: "OPN Testnet",
} as const;

export const STAKING_CONFIG = {
  DEFAULT_APY_BPS: 1000, // 10%
  BPS_DENOMINATOR: 10_000,
  DAYS_PER_YEAR: 365,
} as const;
