import { ethers, run, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("\n╔══════════════════════════════════════════════════════════╗");
  console.log("║        Megicula Stake — Deploy MegiculaToken            ║");
  console.log("╚══════════════════════════════════════════════════════════╝\n");

  const [deployer] = await ethers.getSigners();
  const balance = await ethers.provider.getBalance(deployer.address);

  console.log("  Network      :", network.name);
  console.log("  Chain ID     :", (await ethers.provider.getNetwork()).chainId);
  console.log("  Deployer     :", deployer.address);
  console.log("  Balance      :", ethers.formatEther(balance), "OPN\n");

  // ─── Deploy ────────────────────────────────────────────────────

  console.log("  Deploying MegiculaToken...");

  const TokenFactory = await ethers.getContractFactory("MegiculaToken");
  const token = await TokenFactory.deploy();
  const receipt = await token.deploymentTransaction()?.wait();

  const tokenAddress = await token.getAddress();
  const txHash = receipt?.hash ?? "N/A";

  console.log("  ┌──────────────────────────────────────────────────────┐");
  console.log(`  │  Contract Address : ${tokenAddress}`);
  console.log(`  │  Transaction Hash : ${txHash}`);
  console.log(`  │  Gas Used         : ${receipt?.gasUsed?.toString() ?? "N/A"}`);
  console.log("  └──────────────────────────────────────────────────────┘\n");

  // ─── Explorer URL ──────────────────────────────────────────────

  const explorerBase = network.name === "opnTestnet"
    ? "https://testnet.opnscan.io"
    : `https://${network.name}.etherscan.io`;

  console.log("  Explorer:");
  console.log(`    Contract : ${explorerBase}/address/${tokenAddress}`);
  console.log(`    Tx       : ${explorerBase}/tx/${txHash}\n`);

  // ─── Save to frontend config ──────────────────────────────────

  saveContractAddress("MEGICULA_TOKEN_ADDRESS", tokenAddress, explorerBase);

  // ─── Verify (skip for localhost / hardhat) ─────────────────────

  const etherscanKey = process.env.ETHERSCAN_API_KEY || "";

  if (network.name !== "hardhat" && network.name !== "localhost") {
    if (etherscanKey && etherscanKey !== "placeholder") {
      console.log("  Waiting for block confirmations...");
      await token.deploymentTransaction()?.wait(5);

      try {
        console.log("  Verifying contract on explorer...");
        await run("verify:verify", {
          address: tokenAddress,
          constructorArguments: [],
        });
        console.log("  [OK] Contract verified!\n");
      } catch (error: any) {
        if (error.message.includes("Already Verified")) {
          console.log("  [OK] Contract already verified.\n");
        } else {
          console.log("  [WARN] Verification failed:", error.message);
        }
      }
    } else {
      console.log("  [SKIP] Auto-verification skipped (no ETHERSCAN_API_KEY).");
    }

    console.log("  Verify manually:");
    console.log(`    npx hardhat verify --network ${network.name} ${tokenAddress}\n`);
  } else {
    console.log("  [SKIP] Verification skipped (local network).\n");
  }

  console.log("  Token deployment complete!\n");
}

function saveContractAddress(key: string, address: string, explorerBase: string) {
  const configDir = path.join(__dirname, "..", "frontend", "config");
  const configFile = path.join(configDir, "contracts.ts");

  // Ensure directory exists
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  // Read existing or create new
  let content = "";
  if (fs.existsSync(configFile)) {
    content = fs.readFileSync(configFile, "utf-8");
  } else {
    content = `// Auto-generated by deployment scripts
// Do not edit manually

export const CONTRACTS = {
`;
  }

  // Update or add the key
  const regex = new RegExp(`${key}:\\s*"[^"]*"`, "g");
  if (content.includes(`${key}:`)) {
    content = content.replace(regex, `${key}: "${address}"`);
  } else {
    // Add before closing brace
    content = content.replace(/};\s*$/, `  ${key}: "${address}",\n};\n`);
  }

  fs.writeFileSync(configFile, content, "utf-8");
  console.log(`  [OK] Saved ${key} to frontend/config/contracts.ts`);
}

main().catch((error) => {
  console.error("\n  [ERROR]", error.message);
  process.exitCode = 1;
});
